<a href="https://colab.research.google.com/github/ndb796/Deep-Learning-Basic-for-KISA/blob/master/PyTorch%EC%9D%98_Tensor.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### <b>Tensor 만들기</b>

In [ ]:
import torch

# 리스트를 Tensor로 변환
a = torch.tensor([1, 2, 3])
print(a)

# 값이 초기화되지 않은 행렬을 생성
a = torch.empty(4, 5)
print(a)

# 랜덤 값(uniform)으로 초기화된 행렬을 생성 (기본: 실수형)
a = torch.rand(4, 5)
print(a)

# 0으로 초기화된 행렬을 생성 (정수형)
a = torch.zeros((5, 3), dtype=torch.long)
print(a)

tensor([1, 2, 3])
tensor([[2.7287e-36, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00],
        [0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00, 0.0000e+00]])
tensor([[0.8527, 0.0309, 0.6508, 0.5501, 0.1615],
        [0.7001, 0.7300, 0.4202, 0.5947, 0.4684],
        [0.5614, 0.0432, 0.1355, 0.1070, 0.9445],
        [0.4255, 0.8141, 0.5428, 0.9845, 0.4888]])
tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


### <b>Tensor 더하기</b>

In [ ]:
import torch

# Tensor를 만들고 크기를 출력
a = torch.tensor([1, 1])
print(a.size())

# Tensor 더하기
b = torch.tensor([2, 3])
c = a + b

print(c)

torch.Size([2])
tensor([3, 4])


### <b>Tensor 곱하기</b>

* 기본적인 Tensor의 곱셈은 동일한 위치의 원소끼리 곱하는 연산을 의미합니다.

In [ ]:
import torch

# Tensor 곱하기
a = torch.tensor([[0, 1], [2, 3]])
b = torch.tensor([[1, 2], [3, 4]])
c = a * b

print(c)

tensor([[ 0,  2],
        [ 6, 12]])


### <b>Tensor의 행렬 곱</b>

* Tensor는 행렬 곱 연산을 지원합니다.

In [ ]:
import torch

# Tensor 곱하기
a = torch.tensor([[0, 1], [2, 3]])
b = torch.tensor([[1, 2], [3, 4]])
c = torch.matmul(a, b)

print(c)

tensor([[ 3,  4],
        [11, 16]])


### <b>서로 다른 형태의 Tensor 연산</b>

* 브로드캐스트: 형태가 다른 행렬을 연산할 수 있도록 행렬의 형태를 동적으로 변환합니다.

In [ ]:
import torch

# Tensor 브로드캐스트
a = torch.tensor([1, 2, 3])
b = torch.tensor([[1, 2, 3], [1, 2, 3]])
c = a + b

print(c)

tensor([[2, 4, 6],
        [2, 4, 6]])


### <b>Tensor 형태 변경</b>

* Tensor는 인덱싱 표기법을 사용할 수 있습니다.
* 다양한 방법으로 형태를 변경할 수 있습니다.

In [ ]:
import torch

a = torch.tensor([
    [0, 1, 2, 3],
    [4, 5, 6, 7],
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])

print(a[:, 2])
a = a.view(16)
print(a)
a = a.view(4, 4)
print(a)
a = a.view(-1, 8)
print(a)

tensor([2, 6, 2, 6])
tensor([0, 1, 2, 3, 4, 5, 6, 7, 0, 1, 2, 3, 4, 5, 6, 7])
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7],
        [0, 1, 2, 3],
        [4, 5, 6, 7]])
tensor([[0, 1, 2, 3, 4, 5, 6, 7],
        [0, 1, 2, 3, 4, 5, 6, 7]])


### <b>Tensor와 NumPy 변환</b>


In [ ]:
import torch
import numpy as np

a = torch.tensor([
    [0, 1, 2, 3],
    [4, 5, 6, 7]
])
print(a)

b = a.numpy()
print(b)

c = torch.from_numpy(b)
print(c)

tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
[[0 1 2 3]
 [4 5 6 7]]
tensor([[0, 1, 2, 3],
        [4, 5, 6, 7]])
